python insider.py
python alts.py
python inside_data.py
python banks.py
python otc.py
python cigar_butts.py
python insurance.py
python common_stocks.py
python foreign_stocks.py
python -W ignore Original_Fundamentals.py
python leap_finder.py
python leap_allocation.py
python aesop.py
python abv.py
python stocks_manager.py
python portfolio_manager.py
python first_tier.py
python intersect.py
python intersect_graphs.py
python make_graphs.py
